version: '3'
services:
  courses:
    image: techcursos
    build: ./dockerfiles
    hostname: courses
    expose:
      - '5000'
    volumes:
      - './course:/servico'
    command: python3 servico.py
    networks:
      coursesnet:
        ipv4_address: 172.29.1.1

  bancodados:
    image: mysql
    hostname: bancodados
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
    networks:
      coursesnet:
        ipv4_address: 172.29.1.2

  mongo:
    image: mongo
    ports:
      - '27018:27017'

  networks:
    coursesnet:
      ipam:
        driver: default
        config:
          - subnet: 172.29.1.0/16
