version: '3'
services:
  cursos:
    image: techcursos
    build: ./dockerfiles
    hostname: cursos
    expose:
      - '5000'
    volumes:
      - './cursos:/servico'
    command: python3 servico.py
    ports:
      - '8088:5000'
  favoritos:
    image: techcursos
    build: ./dockerfiles
    hostname: favoritos
    expose:
      - '5000'
    volumes:
      - './favoritos:/servico'
    command: python3 servico.py
    ports:
      - '8089:5000'
  avaliacao:
    image: techcursos
    build: ./dockerfiles
    hostname: avaliacao
    expose:
      - '5000'
    volumes:
      - './avaliacao:/servico'
    command: python3 servico.py
    ports:
      - '8090:5000'
  cursosiniciados:
    image: techcursos
    build: ./dockerfiles
    hostname: cursosiniciados
    expose:
      - '5000'
    volumes:
      - './cursosiniciados:/servico'
    command: python3 servico.py
    ports:
      - '8091:5000'
  comentarios:
    image: techcursos
    build: ./dockerfiles
    hostname: comentarios
    expose:
      - '5000'
    volumes:
      - './comentarios:/servico'
    command: python3 servico.py
    ports:
      - '8092:5000'
  bd:
    image: mysql
    hostname: bd
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '3307:3306'
